import Layout from "@/components/Layout";
import { Providers } from "./providers";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        style={{
          margin: "0",
          padding: "0",
          boxSizing: "border-box",
          height: "100vh",
        }}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
